# Generated by Django 4.0.2 on 2022-02-03 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('hire_date', models.DateField(null=True)),
                ('enrollment_date', models.DateField(null=True)),
                ('discriminator', models.CharField(default='Instructor', max_length=128)),
            ],
        ),
    ]
